name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: [ 2.5, 2.6, 2.7, '3.0' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Test
      run: |
        bundle exec rspec ./spec
